const express = require('express');
const dotenv = require("dotenv");
const cors = require('cors');
const { contactForm } = require('./src/contactForm');
dotenv.config();
const app = express();
const PORT = process.env.PORT || 3000;
app.use(cors({ origin: process.env.ALLOWED_ORIGINS }));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.get('/', (req, res) => res.send('Backend is running!'));
app.post('/contact', contactForm);
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));